controller_list:
 - name: arm_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - j01
      - j02
      - j03
      - j04
      - j05
      - j06
