controller_list:
  - name: fake_welding_arm_controller
    joints:
      - j01
      - j02
      - j03
      - j04
      - j05
      - j06
initial:  # Define initial robot poses.
  - group: welding_arm
    pose: Home